<a href="https://colab.research.google.com/github/sofiiamyshelova-prog/python_for_ds_tasks/blob/main/Copy_of_HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [9]:
import numpy as np
vector=np.random.rand(10)
print("вектор:")
print(vector)
print("розмірність вектора", vector.shape)

matrix=np.array([[11, 14, 17],
                 [20, 23, 26],
                 [29, 32, 35]])
print("\nматриця B:")
print(matrix)
print("розмірність матриці", matrix.shape)

вектор:
[0.56413943 0.2546758  0.07039649 0.37093528 0.27559532 0.32108469
 0.42284966 0.14915743 0.07087914 0.92856175]
розмірність вектора (10,)

матриця B:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
розмірність матриці (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [20]:
vector_plus10=np.round(vector+10,2)
print("\nвектор +10:", vector_plus10)

matrix_mult2=2*matrix
print("\nматриця *2:\n", matrix_mult2)

vector_squared=np.square(vector)
print("\nвектор поелементно в квадраті", vector_squared)

#або квадрат кожного значення нового вектор +10
vector_plus10_squared=np.square(vector_plus10)
print("\nновий вектор поелементно в квадраті",vector_plus10_squared)


вектор +10: [10.56 10.25 10.07 10.37 10.28 10.32 10.42 10.15 10.07 10.93]

матриця *2:
 [[22 28 34]
 [40 46 52]
 [58 64 70]]

вектор поелементно в квадраті [0.31825329 0.06485976 0.00495567 0.13759298 0.07595278 0.10309538
 0.17880183 0.02224794 0.00502385 0.86222693]

новий вектор поелементно в квадраті [111.5136 105.0625 101.4049 107.5369 105.6784 106.5024 108.5764 103.0225
 101.4049 119.4649]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [21]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [24]:
result_matrix = np.dot(B, A)
print("\nBA\n",result_matrix)
print("\nBA*C\n",np.dot(result_matrix, C))
print("\nBA*D\n",np.dot(result_matrix, D))


BA
 [[0.7281 0.5202]
 [0.2034 0.2846]]

BA*C
 [[0.5202]
 [0.2846]]

BA*D
 [[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [32]:
result_matrix_T=result_matrix.T
print("(BA)^T\n:",result_matrix_T)

vector_T=vector.T
print("\n vector^T",vector_T)
print("розмірність транспонованого вектора", vector_T.shape)
#розмірність така ж, але припускаю, що він має стати рядком, якщо "звичайний" вектор - це стовпець

column_vector=np.expand_dims(vector,axis=1)
print("\n column_vector\n",column_vector)
print("розмірність column_vector", column_vector.shape)
#тепер вектор став стовпцем

column_vector_T=column_vector.T
print("\n column_vector^T",column_vector_T)
print("розмірність транспонованого column_vector", column_vector_T.shape)
#тепер він рядок

(BA)^T
: [[0.7281 0.2034]
 [0.5202 0.2846]]

 vector^T [0.56413943 0.2546758  0.07039649 0.37093528 0.27559532 0.32108469
 0.42284966 0.14915743 0.07087914 0.92856175]
розмірність транспонованого вектора (10,)

 column_vector
 [[0.56413943]
 [0.2546758 ]
 [0.07039649]
 [0.37093528]
 [0.27559532]
 [0.32108469]
 [0.42284966]
 [0.14915743]
 [0.07087914]
 [0.92856175]]
розмірність column_vector (10, 1)

 column_vector^T [[0.56413943 0.2546758  0.07039649 0.37093528 0.27559532 0.32108469
  0.42284966 0.14915743 0.07087914 0.92856175]]
розмірність транспонованого column_vector (1, 10)
